export const KEYS = {
  category_list: "category_all",
  category_properties: "category_properties",
  category_filter: "category_filter",
  product_list: "product_list",
  product: "product",
  product_string_values: "product_string_values",
  file_upload: "file_upload",
  user_update: "user_update",
  district: "district",
  region: "region",
  payment_type: "payment_type",
  sell_type: "sell_type",
  favorite_product_remove: "favorite_product_remove",
};
