export const URLS = {
  category: "/category",
  category_list: "/category/all",
  category_properties: "/category/properties",
  category_filter: "/category/get-filters",
  product_list: "/product/list",
  product: "/product",
  product_string_values: "/product/string-values",
  file_upload: "/file/upload",
  user_update: "/user/26",
  district: "/district/all",
  region: "/region/all",
  payment_type: "/payment-type/all",
  sell_type: "/sell-type/all",
  favorite_product_remove: "/favorite-product/remove",
};
